services:
  training:
    build: ./training
    container_name: vrce-training
    volumes:
      - ./models:/app/models
      - ./training/data:/app/data

  inference:
    build: ./inference
    container_name: vrce-inference
    ports:
      - "3000:3000"
    volumes:
      - ./models:/app/models
    depends_on:
      - training
